export const ROUTES = {
  CHAT: "/chat",
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  INVENTORY: "/inventory",
  PRODUCT_NEW: "/inventory/new",
  PRODUCT_EDIT: "/inventory/:id",
  SCANNER: "/scanner",
  ALERTS: "/alerts",
  PROFILE: "/profile",
  FOOD_STATUS: "/food-status",
}
